### ISSUE TITLE
Fix spacing between Social Media Bubbles on Mobile

### ISSUE THREAD

**Issue by SonicKim** [lukeburns/costa2018.com#14]
Need to add a space between two Social Media Bubbles on Mobile

**Comment by SonicKim** [comment]
![img_5437](https://user-images.githubusercontent.com/26078184/29790963-601b1d34-8c09-11e7-8b42-aee223e9dda4.PNG)

**Comment by lukeburns** [comment]
How's that?

**Comment by SonicKim** [comment]
Nice!
