### ISSUE TITLE
Need to add Terms, Conditions, Security

### ISSUE THREAD

**Issue by SonicKim** [lukeburns/costa2018.com#15]
We'll need to add the terms and conditions content to the site. Let's discuss what that content is and where to put it!

**Comment by SonicKim** [comment]
The content we have is here (thanks Costa!): https://docs.google.com/document/d/1qwSmjHH0A0dDvvvGdFMBUM_WBveCuJhjmYNRzIR5sK4/edit?ts=59a5813b#heading=h.gc63z3ixog8y

**Comment by wamoyo** [comment]
We need a lawyer to eventually review this kind of stuff, but ideally I would like to keep it readable, and understandable. It's kind of useless if it's written in lawyer speak.

**Comment by lukeburns** [comment]
Live!
