### ISSUE TITLE
Link Bank Account with Stripe Account

### ISSUE THREAD

**Issue by lukeburns** [lukeburns/costa2018.com#16]
Need this to accept donations on website

**Comment by wamoyo** [comment]
Yeah, we gotta get this sorted. @SonicKim, wanna call the bank tomorrow?

**Comment by SonicKim** [comment]
Hey. Sorry for the delay. I still haven't been able to reach David our contact at the bank so we're still waiting on this. I'll let you guys know when there's an update.

**Comment by wamoyo** [comment]
We can always try to switch banks. Thoughts on a bank? I like Ally, and CapitalOne very much, but I don't know that they support the type of account we need. Wanna call them tomorrow?

**Comment by SonicKim** [comment]
I just got off the phone with David. Still waiting on approval from their compliance dept. but he's assured me that he will give me an answer one way or the other by tomorrow at the very latest. Hopefully today.

**Comment by wamoyo** [comment]
Perfect : ) It's nice when things have a known timing.

**Comment by SonicKim** [comment]
So David never got back to me. I called a few times today and he's been out of the office again. I'm going to start working on a different bank on Tuesday (after labor day)

Really not ideal but I'm not sure what else we can do.

Hopefully we'll push this next week and keep moving forward. Sorry sorry

**Comment by lukeburns** [comment]
Donation link up and running 👍
