### ISSUE TITLE
Changing Donor Box Amounts

### ISSUE THREAD

**Issue by SonicKim** [lukeburns/costa2018.com#26]
We'd like to change the amounts listed in the website donor box. Do need to do this through Donor Box? Have we set up a login with them? If so, I'm not sure I have the username/pw...

We want to make it $25, $50, $100, Custom.

**Comment by wamoyo** [comment]
So, just so I know. @SonicKim you have access to make these changes, or only Luke?

**Comment by SonicKim** [comment]
I have access now. It's already changed. woot woot
