### ISSUE TITLE
District 3 Blurb. And maybe map.

### ISSUE THREAD

**Issue by SonicKim** [lukeburns/costa2018.com#27]
Hey guys,

I've heard this a couple times now but it seems it's not explicitly clear from the site that Costa is running for Congress.

I've heard a few "If you didn't tell me, I'm not sure I would've known." or "I thought this might be a consultant thing" Something like this. 

I think the easy solve would be to under the logo put "Candidate for US Congress - NY D3"

Maybe there's a place for a map of district three?

Thoughts?

**Comment by wamoyo** [comment]
That's a great point! 

Here's a easy image:

![ny-03](https://user-images.githubusercontent.com/1170326/31245539-b05cdc28-a9d8-11e7-8f27-2ffdcdf3f6e3.png)

And maybe put a link under it, or have the image link to your voter lookup: https://voterlookup.elections.state.ny.us/ which reports your congressional district among other things.

**Comment by SonicKim** [comment]
This map is okay. The water being white and brighter than the land makes it a little confusing at first glance. Just a thought I had.

**Comment by wamoyo** [comment]
I can change the colors. Any suggestions?

**Comment by SonicKim** [comment]
Maybe just flip the grey and the white and see if it's better. I like green! Luke likes purple! hahah

**Comment by wamoyo** [comment]
How this?

![ny-03](https://user-images.githubusercontent.com/1170326/31246793-8c989ada-a9dc-11e7-9781-1f31e9ee52c4.png)

**Comment by SonicKim** [comment]
Too many colors. The blue distracts from the green.

**Comment by wamoyo** [comment]
Okay. Trying the flip you mentioned... 

![ny-03](https://user-images.githubusercontent.com/1170326/31247104-96c92c1c-a9dd-11e7-8e5d-6cb4ac1c2485.png)

**Comment by wamoyo** [comment]
I'm not the president, but I'm gonna veto that.

**Comment by SonicKim** [comment]
Yeah the flipped is lame too.

Do the blue one, but grey the blue out a bit. A less bright blue will help it, I think. Thanks, Costa! Fine job!

**Comment by wamoyo** [comment]
I still like the original the best. White is just neutral... 

![ny-03](https://user-images.githubusercontent.com/1170326/31247920-121bb07c-a9e0-11e7-98bf-912a1fb0a1ad.png)

**Comment by wamoyo** [comment]
![ny-03](https://user-images.githubusercontent.com/1170326/31247959-319f8590-a9e0-11e7-8c03-f462696831cb.png)

**Comment by SonicKim** [comment]
Hahahah Okay. I like the original, the blue one, and the last one the best now. 

You can choose!

**Comment by wamoyo** [comment]
Doesn't matter. Whatever looks nice on the site.

**Comment by SonicKim** [comment]
Go with the original. It's great!

**Comment by SonicKim** [comment]
Thanks for exploring some options! :)

**Comment by lukeburns** [comment]
PURPLE PLEASE

On Thu, Oct 5, 2017 at 3:33 PM, Sonic Kim <notifications@github.com> wrote:
Thanks for exploring some options! :)

**Comment by wamoyo** [comment]
Map added : )
